name = "SPC-X-POC"
scheduler = "slurm"

install_path = "./install"
output_path = "./results"
default_partition = "ISR1-PRE"
#default_partition = "ISR1-ALL"
cache_docker_images_locally = true

gpus_per_node = 8
ntasks_per_node = 8

[partitions]
  [partitions.ISR1_PRE]
  name = "ISR1-PRE"
  nodes = ["hgx-isr1-pre-[01-16]"]
  [partitions.ISR1-ALL]
  name = "ISR1-ALL"
  nodes = ["hgx-isr1-[004-024]"]

[global_env_vars]
  # NCCL General Configuration
  NCCL_SOCKET_IFNAME = "eno8303"

  # NCCL InfiniBand (IB) Specific Configurations
  NCCL_IB_GID_INDEX = "3"
  NCCL_IB_TC = "96"
  NCCL_IB_HCA = "=mlx5_0:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"
  NCCL_IB_TIMEOUT = "20"
  NCCL_NET_PLUGIN = "none"
  NCCL_IB_ADAPTIVE_ROUTING = "1"
  NCCL_IB_SPLIT_DATA_ON_QPS = "0"
  NCCL_IBEXT_DISABLE = "0"
  NCCL_COLLNET_ENABLE = "0"
  NCCL_SHM_DISABLE = "0"
  NCCL_P2P_DISABLE = "0"
  NCCL_CROSS_NIC = "1"

  # Device Visibility Configuration
  MELLANOX_VISIBLE_DEVICES = "0,3,4,5,6,9,10,11"
  CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7"

  NCCL_DEBUG = "none"
 

  

 
