name = "single_nccl_test"
# NCCL_TESTS_SPLIT_MASK=0x7
[Tests]
  [Tests.1]
    name = "nccl_test_reduce_scatter"
    nodes = ["hgx-isr1-pre-[01,05,09,13]"]
    [Tests.1.dependencies]
      start_post_comp = {}
      end_post_comp = {}

